name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Neovim
        run: |
          curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz
          tar xvf nvim-linux-x86_64.tar.gz
          sudo cp -r nvim-linux-x86_64/bin/* /usr/local/bin/
          sudo cp -r nvim-linux-x86_64/lib/* /usr/local/lib/
          sudo cp -r nvim-linux-x86_64/share/* /usr/local/share/

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Run tests
        run: |
          make
          make test
